config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
   
  namespace :admin do

    # TODO - how should this work ???
    # use put as essentially the select is to modify an existing entry with different product
     
    resources :products_taxons do
      delete :remove
    end
    
    resources :taxons do
      resources :products_taxons do
        collection do
          post :update_positions
          post :select
        end
      end
    end

  
    resources :taxons do
      put :reorder_products
    end
    
  end
end

app/models/spree/product_decorator.rb
module Spree
  Product.class_eval do

    has_many :products_taxons, :dependent => :destroy
    has_many :taxons, :through => :products_taxons#, :order => :position
  end
end

app/models/spree/products_taxon.rb
# Added a position column to enable ordering other than by name

module Spree
  class ProductsTaxon < ActiveRecord::Base
    belongs_to :product
    belongs_to :taxon

    #acts_as_list :scope => :taxon
          
    default_scope :order => '0+spree_products_taxons.position ASC'

    
    before_save :set_position

    protected

    def set_position
      self.position ||= 1 + (ProductsTaxon.where('txon_id=?', taxon_id).maximum(:position) || 0)
    end

  end
end

app/models/spree/taxon_decorator.rb
module Spree
  
  Taxon.class_eval do

    MENU_LOCATIONS = [:top, :left, :right, :bottom, :sidebar, :footer]
    
    has_many :products_taxons
    has_many :products, :through => :products_taxons

    accepts_nested_attributes_for :products_taxons, :allow_destroy => true

    attr_accessible :menu, :menu_index
    
    # TODO - research who 'def applicable_filters' works, 
    # could/should we add the ProductsTaxons ordering as a filter ?
           
    scope :for_menu,  lambda { |*args| { :conditions => ["menu = ?", args.first || :top], :order => :menu_index } }

    def css_name
      self.name.gsub(' ','_')
    end

  end

end

app/controllers/spree/admin/products_taxons_controller.rb
module Spree
  
  module Admin
    class ProductsTaxonsController < ResourceController

      before_filter :load_object, :only => [:remove]

      def index
        @taxons = Spree::Taxon.find(:all, :order => 'name')
    
        # These Products will be available to be added to Taxons  
        @all_available_products = Spree::Product.active
      end

      def update_positions
        # the js table helper gives us back params list for 

        logger.info params.inspect 
        taxon = Spree::Taxon.find(params[:taxon_id])

        product_taxons = taxon ? taxon.products_taxons() : []
        
        puts "\n\n################## FIND IDS", product_taxons.inspect, params[:positions].inspect
        
        # js table helper gives list 4 every table (taxon) with the product_taxoins ids as VALUES
        # keys are the new position in the list
        # 
        # not nice if we have huge product/taxons lists but this is what the js returns us
        # so bit stuffed for now 
        
        params[:positions].each do |index, moved_pt_id| 
          break if(product_taxons.empty?)
        
          product_taxons.each_with_index do |pt, i| 
            if(pt.id == moved_pt_id.to_f)
              puts "MATCH #{pt.id} #{pt.position} => #{index}"
              pt.update_attribute(:position, index)
              product_taxons.delete_at(i)
              break
            end
          end
        end    
                
        respond_to do |format|
          format.html { redirect_to admin_product_variants_url(params[:taxon_id]) }
          format.js  { 
            message = taxon ? "Ok" : "Sorry could not find the supplied Taxon"
            render :text => message
          }
        end
      end
      
      # AJAX method for selecting a Product and associating with a Taxon
      
      # select_admin_taxon_products_taxons_url(taxon)
      
      def select
        
        logger.info params.inspect 
        taxon = Spree::Taxon.find(params[:taxon_id])

       # @product = Spree::Product.find(params[:product])
      #  @taxon   = Spree::Taxon.find(params[:id])

       # if(@product && @taxon)
       #   @product_taxon = Spree::ProductsTaxon.create(:taxon => @taxon, :product => @product)
       #   @taxon.reload
       # end

        #set_available


       # @update_table_dom = params[:dom]

      ##  respond_to do |format|
          format.html
       #   format.js  { render :partial => 'select', :layout => false}
        #end

      end

      # AJAX method for removing a Product from association with a Taxon

      def remove

        object.delete

        respond_to do |format|
          format.html
          format.js { render(:nothing => true) }
        end
      end


      def set_available
        @available = Spree::Product.active

        @available_products  = @available - @taxon.products
      end

    end
  end
end

app/controllers/spree/admin/taxons_controller_decorator.rb
module Spree
  module Admin
    TaxonsController.class_eval do
      before_filter :load_object, :only => [:set_page, :selected, :available, :remove]
      before_filter :load_pages, :only => [:index, :new, :edit, :selected]


      def reorder_products
 
        @taxon = Taxon.find(params[:id])
        if(@taxon)
          # Not sure how or if possible to do this all in one line @taxon.update_attributes chokes
          params[:taxon][:products_taxons].each do |id, attributes|
            x = ProductsTaxon.find(id)
            x.update_attributes( attributes) if(x)
          end if params[:taxon][:products_taxons]
    
          respond_to do |format|
            format.html
            format.js  { render :nothing => true, :status => :ok }
          end
        end

      end

      def set_page
        @taxon.update_attributes( :page_id => params[:page] )
      end

      # Over ride existing method to call set_available
      def selected
        @taxons = @product.taxons
        set_available
      end

      # AJAX method for selecting an existing ProductProperty and associating with the current product
      def select
        @product = Product.find(params[:product_id])
        @taxon = Taxon.find(params[:id])
        @product.taxons << @taxon
        @product.save
        @product.reload
        set_available
        render :partial => 'table', :layout => false
      end

      def remove
        @product.taxons.delete(@taxon)
        @product.save
        @product.reload
        set_available
        respond_to do |format|
          format.html
          format.js {render :partial => 'available', :layout => false}
        end
      end

      # Called from the search function
      def available
        set_available
        respond_to do |format|
          format.html
          format.js {render :partial => 'available', :layout => false}
        end
      end

      def set_available
        if params[:q].blank?
          @available = Taxon.find(:all, :order => 'name')
        else
          @available = Taxon.find(:all, :conditions => ['lower(name) LIKE ?', "%#{params[:q].downcase}%"])
        end
        @available = @available - @product.taxons
      end

      private
  
      def load_pages
        @pages = Page.all
      end

    end
  end
end

app/controllers/spree/taxons_controller_decorator.rb
module Spree
  
  TaxonsController.class_eval do
 
    private
    def load_data
      @taxon ||= object
      retrieve_products

      @products = @products.sort do |p1, p2|
        t1 = p1.products_taxons.detect{|pt| pt.taxon == @taxon}; t2 = p2.products_taxons.detect{|pt| pt.taxon == @taxon};
        pos1 = t1 ? t1.position : 0; pos2 = t2 ? t2.position : 0
        pos1 <=> pos2
      end
      @products
    end

  end
end

app/views/spree/admin/products_taxons/_table.html.erb
<%= javascript_tag do -%>

  $(document).ready(function() {
    $('#<%= dom_id(taxon, :product_list) -%>').click(function(event){
    
    // make a POST call send the Product ID from the select drop down list replace the content
    
    alert($('#<%= dom_id(taxon, :select_add_product) -%>').val() );

    // :method => :post,
    //$.post("<%= select_admin_taxon_products_taxons_url(taxon) -%>", function(data) {
      //  $("#results").html( "#{dom_id(taxon, :product_list)} -%>");
    //});
    });
  });

<% end  %>

<div id="results"></div>

<ul class="actions">
  <li id=<%= "#{dom_id(taxon, :add_product)}" -%>>
    <%  available_products  = @all_available_products - taxon.products %>
    <%= select_tag dom_id(taxon, :select_add_product), options_for_select(available_products.collect{ |p| [p.name, p.id] }.insert(0, ''), 0)%>

    </br>
    <%= link_to icon('add') + ' ' + t("add_product"), "#", :remote=>true, :id => dom_id(taxon, :product_list) %>
  </li>
</ul>

app/views/spree/admin/products_taxons/index.html.erb
<% content_for :head do %>

  <style type="text/css">
    hr {
      margin: 0.8em 0 0.4em 0; color: #f00;
      background-color: #00b29e;
      height: 4px;
      border: 1px solid red;
    }

    strong.products_taxons {
      padding: 0 0 0 12px; 
      color: #00b29e; font-size: 14px; font-weight: bold;
    }

    #products_taxons_taxon_details { padding: 24px 0 0 0; }

    div.products_taxons {
      padding: 12px; 
      border: 1px solid black;
      float: left; width: 96%;
      margin-bottom: 24px;
    }

    #products_taxons_product_mngmnt
    {
      border: 1px solid #00b29e;
      float: left; width: 96%;
    }

    #products_taxons_products
    {
      border: 1px solid #00b29e; width: 30%; float: left;
    }

    table.products_taxons_listing_products { }

    #products_taxons_available
    {
      padding-top: 12px; float: right;
    }

    #products_taxons_available ul {
      list-style-type: none;
    }
    
    #products_taxons_available a, #products_taxons_available select{
      float: right;
    }

  </style>
<% end %>


<%= render :partial => 'spree/admin/shared/product_sub_menu' %>

<h1 class="products_taxons"><%= t(:products_taxons) %></h1>

<% @taxons.each do |taxon| %>
  <div class="products_taxons">
    <b>Taxon:</b><strong class="products_taxons"><%= taxon.name %></strong>
    <table id="products_taxons_taxon_details">
      <thead>
        <tr>
          <th><%= t('icon') %></th>
          <th><%= t("description") %></th>
          <th><%= t("menu") %></th>
          <th><%= t("menu index") %></th>
        </tr>
      </thead>
      <tbody>
        <tr id="<%= dom_id(taxon, :sel)%>">
          <td width="40%"><%= taxon.icon %></td>
          <td><%= taxon.description %> </td>
          <td><%= taxon.menu %> </td>
          <td><%= taxon.menu_index %> </td>
          </td>
        </tr>
      </tbody>
    </table>

    <div id="products_taxons_product_mngmnt">

      <div id="products_taxons_products">
        <table class="sortable products_taxons_listing_products" id="listing_products<%= taxon.id -%>" data-hook="roducts_taxons_table" data-sortable-link="<%= update_positions_admin_taxon_products_taxons_url(taxon) %>">
          <thead>
            <tr><th colspan="2"><h4>Product Listing</h4></th></tr>
          </thead>
          <tbody>
            <% taxon.products_taxons.each do |pt| %>
              <tr class="spree_products_taxons <%= cycle('odd', 'even')%>" id="<%= spree_dom_id pt %>" data-hook="products_taxons_row">
                <td><span class="handle"></span> <%= pt.product.name %></td>
                <td width="10%"><%= link_to_delete(pt) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div id="products_taxons_available">
        <%= render :partial => 'table', :locals => {:taxon => taxon} %>
      </div>
    </div>
  </div>
  <br class="clear">
<% end %>

app/views/spree/admin/shared/_product_sub_menu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav" data-hook="admin_product_sub_tabs">
    <%= tab :products, :match_path => '/products' %>
    <%= tab :option_types, :match_path => '/option_types' %>
    <%= tab :properties %>
    <%= tab :prototypes %>
    <%= tab(:products_taxons) %>
  </ul>
<% end %>